import type { Metadata } from "next";
import { Libre_Baskerville, Quicksand } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const libre = Libre_Baskerville({ 
  subsets: ['latin'], 
  weight: ['400', '700'], 
  variable: '--font-libre' 
});

const quicksand = Quicksand({ 
  subsets: ['latin'], 
  weight: ['400', '500', '700'], 
  variable: '--font-quicksand'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${libre.variable} ${quicksand.variable} antialiased`}
          suppressHydrationWarning
          style={{ fontFamily: "var(--font-libre )" }}
        >
          <Navigation />
            <main >
              {children}
            </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
